### ISSUE TITLE
Warning when pushing a new version to Merritt

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/MerrittLink#2]
Would it be possible to have some sort of pop-up warning alerting the Admin that one or more of the items they've selected for export to Merritt are already in Merritt (thus creating a new version in Merritt)?

**Comment by NedHenry** [comment]
That is definitely possible, and should not take very long. I will look into it. Thanks!

**Comment by NedHenry** [comment]
I added this popup alert ("modal dialog") functionality in the newest version of the plugin. Please let me know if there are any issues with this feature.
